# Site settings
title: "Adesh Singh"
description: "QT Software Developer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Adesh Singh"
resume_title:                   "QT Software Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "adeshworkmail@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 8305516312"
resume_contact_address:         "IMT Manesar Gurugram Haryana Bharat"

resume_header_contact_info:     "IMT Manesar Gurugram Haryana Bharat • +91 8305516312 • adeshworkmail@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am currently working as QT software developer. I am a Developer with an interest in learning new things and technologies. Also has knowledge on data structures, Embedded Software , QT QML UI development for Embedded as well as desktop and Object-Oriented Programming.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/cppqtdev"
  resume_twitter_url:           "http://twitter.com/divyadesh_777"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://in.linkedin.com/in/adesh-singh-9a882316a"
  resume_instagram_url:         "http://instagram.com/divyadesh_777"
  resume_website_url:           "http://dabreha.blogspot.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
